version: 2
updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore(deps)"
    labels:
      - "Dependencies"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore(actions)"
    labels:
      - "CI"
      - "Dependencies"
