<?php

namespace VCR\Util\Soap;


class SoapClient extends \SoapClient
{
    public function __call($function_name, $arguments)
    {
        parent::__call($function_name, $arguments); // TODO: Change the autogenerated stub
    }

    public function __soapCall($function_name, array $arguments, array $options = null, $input_headers = null, array &$output_headers = null)
    {
        parent::__soapCall($function_name, $arguments, $options, $input_headers, $output_headers); // TODO: Change the autogenerated stub
    }

    public function __doRequest($request, $location, $action, $version, $one_way = 0)
    {
        parent::__doRequest($request, $location, $action, $version, $one_way); // TODO: Change the autogenerated stub
    }


}
