// @ts-check

/**
 * Explicit order (not autogenerated) so it matches the hub table in docs/index.md.
 * docs/index.md itself is intentionally not listed here — it's the homepage (routeBasePath: '/').
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [
    'getting-started',
    'requirements',
    {
      type: 'category',
      label: 'Guides',
      items: [
        'guides/how-vcr-works',
        'guides/cassettes',
        'guides/record-modes',
        'guides/request-matching',
      ],
    },
    {
      type: 'category',
      label: 'How-to',
      items: [
        'howto/use-with-phpunit',
        'howto/use-with-codeception',
        'howto/filter-sensitive-data',
        'howto/custom-request-matcher',
        'howto/select-library-hooks',
        'howto/record-soap',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/vcr-facade',
        'reference/configuration',
        'reference/request-matchers',
        'reference/library-hooks',
        'reference/storage-backends',
        'reference/events',
        'reference/request-response',
      ],
    },
    'upgrading',
    {type: 'doc', id: 'old-changelog', label: 'Old Changelog'},
  ],
};

export default sidebars;
